"""
candidate_strategy.py -- WEATHER FORECAST ARBITRAGE parameters.

This is the file that AutoResearch edits and improves. All parameters
control the weather forecast vs. Kalshi market edge-detection pipeline
in weather_strategy.py.

DO NOT edit this file manually unless you want to reset the strategy.
AutoResearch will evolve it automatically overnight.
"""

# =============================================================================
# WEATHER-SPECIFIC PARAMETERS -- AutoResearch will modify these
# =============================================================================

# Forecast uncertainty: standard deviation in degrees F for NWS forecasts
# Keyed by days_out. Lower = more aggressive (tighter model), higher = more conservative.
FORECAST_STDEV_0 = 1.5   # Same day
FORECAST_STDEV_1 = 2.5   # Tomorrow
FORECAST_STDEV_2 = 3.5   # Day after tomorrow
FORECAST_STDEV_3 = 4.5   # 3 days out

# Edge threshold: minimum edge in cents before we place a trade.
# Too low = many low-quality trades with slippage. Too high = miss good edges.
EDGE_THRESHOLD_CENTS = 3.0

# Position sizing: number of contracts per trade
CONTRACTS_PER_TRADE = 10

# NWS blend ratio: weight given to NWS official forecast vs. ensemble mean.
# 0.0 = pure ensemble, 1.0 = pure NWS official. Currently 40% NWS, 60% ensemble.
NWS_OFFICIAL_WEIGHT = 0.40

# City weights: relative weight for position sizing per city.
# Higher weight = trade more contracts in that city.
CITY_WEIGHT_NYC = 1.0
CITY_WEIGHT_CHI = 0.0   # Disabled 2026-03-22: March 21 forecast off by 9.5°F, need more data
CITY_WEIGHT_MIA = 1.0
CITY_WEIGHT_LA = 1.0
CITY_WEIGHT_DC = 1.0
CITY_WEIGHT_DEN = 1.0

# Market type preference: multiplier on contracts for bucket vs threshold markets.
# >1.0 = prefer that type, <1.0 = trade less of that type.
BUCKET_MULTIPLIER = 1.0
THRESHOLD_MULTIPLIER = 1.0

# Confidence thresholds (edge in cents)
HIGH_CONFIDENCE_EDGE = 7.0  # Above this = "high" confidence
MEDIUM_CONFIDENCE_EDGE = 5.0  # Above this = "medium" confidence

# Maximum position per single market (dollars)
MAX_POSITION_DOLLARS = 5.0

# Minimum volume to consider a market (contracts traded)
MIN_VOLUME = 10

# Ensemble spread filter: if ensemble stdev < this, increase position
# (tighter ensemble = more confident forecast = bigger bet)
TIGHT_ENSEMBLE_THRESHOLD = 2.0
TIGHT_ENSEMBLE_MULTIPLIER = 1.5

# Edge thresholds per strategy (cents). Each strategy has different baseline edge
# requirements reflecting different model confidence levels.
CRYPTO_EDGE_THRESHOLD_CENTS = 4.0   # Crypto (BTC/ETH/SOL) bucket pricing
SPORTS_EDGE_THRESHOLD_CENTS = 5.0   # NBA/sports model-based edges
ARB_EDGE_THRESHOLD_CENTS = 3.0      # Arbitrage (lower threshold, built-in edge)
EXIT_EDGE_THRESHOLD_CENTS = 2.0     # Exit existing position when edge drops below

# Blend weights for day-dependent forecast combination (HRRR + GFS + NWS = 1.0)
BLEND_HRRR_DAY0 = 0.40   # Day 0: HRRR dominant (3km resolution, best short-range)
BLEND_GFS_DAY0 = 0.30     # Day 0: GFS ensemble
BLEND_NWS_DAY0 = 0.30     # Day 0: NWS official
BLEND_HRRR_DAY1 = 0.25    # Day 1: HRRR fading
BLEND_GFS_DAY1 = 0.40     # Day 1: GFS takes over
BLEND_NWS_DAY1 = 0.35     # Day 1: NWS still contributes
BLEND_GFS_DAY2 = 0.60     # Day 2+: No HRRR, GFS dominant
BLEND_NWS_DAY2 = 0.40     # Day 2+: NWS fills remainder


# =============================================================================
# COPY-TRADE PARAMETERS -- AutoResearch will modify these
# =============================================================================

# Minimum confidence to auto-copy a trade (0.0-1.0)
COPY_MIN_CONFIDENCE = 0.8

# How quickly to react after detecting a whale trade (seconds)
# Lower = more aggressive, higher = wait for confirmation
COPY_DELAY_SECONDS = 60

# Position sizing as fraction of what the whale trades
COPY_SIZE_FRACTION = 0.01  # 1% of whale's position

# Maximum copy trades per day
COPY_MAX_TRADES_PER_DAY = 10

# Minimum whale trade size to copy (USD)
COPY_MIN_WHALE_SIZE = 100.0

# Weight per tracked trader (how much to trust their signals)
COPY_TRADER_WEIGHT_0x8dxd = 1.0

# Which categories to copy (multiplier: 0 = skip, 1 = normal, 2 = double)
COPY_CRYPTO_MULT = 1.5
COPY_POLITICS_MULT = 0.0  # Don't copy politics initially
COPY_SPORTS_MULT = 0.5


# =============================================================================
# TAIL FADE PARAMETERS -- AutoResearch will modify these
# =============================================================================

# Maximum YES price (in cents) to fade -- buy NO when YES is this cheap
TAIL_FADE_MAX_PRICE = 20

# Minimum market volume to consider (filter illiquid markets)
TAIL_FADE_MIN_VOLUME = 100

# Category toggles: 1 = enabled, 0 = disabled
TAIL_FADE_WEATHER_ENABLED = 0
TAIL_FADE_CRYPTO_ENABLED = 1
TAIL_FADE_NBA_ENABLED = 0

# Mid-range fade bounds: buy NO when YES price is in this range (cents)
TAIL_FADE_MID_LOW = 45
TAIL_FADE_MID_HIGH = 50


# =============================================================================
# NBA UNDERDOG PARAMETERS -- AutoResearch will modify these
# =============================================================================

# Price range for underdog entries (cents). Buy YES when market price is in this range.
# Based on z=7.04 edge from 56 real trades: underdogs at 10-30c win 46% vs 14% implied.
UNDERDOG_MAX_PRICE = 20  # Upper bound for entry
UNDERDOG_MIN_PRICE = 8  # Lower bound (avoid illiquid near-zero markets)

# Position sizing
UNDERDOG_MAX_BET_DOLLARS = 2  # Maximum dollars per underdog bet
UNDERDOG_MAX_CONTRACTS = 20  # Maximum contracts per single trade

# Market filter: 1 = Winner markets only (proven), 0 = include props too (unproven)
UNDERDOG_WINNER_ONLY = 1


# =============================================================================
# WEATHER TAIL PARAMETERS -- AutoResearch will modify these
# =============================================================================

# Maximum YES price in cents to consider for tail fade (buy NO)
WEATHER_TAIL_MAX_YES = 15

# Minimum model P(NO) required to place a tail trade
WEATHER_TAIL_MIN_NO_PROB = 0.90

# Minimum edge in cents after fees to place a tail trade
WEATHER_TAIL_MIN_EDGE = 0.5

# Maximum contracts per tail trade
WEATHER_TAIL_MAX_CONTRACTS = 3


# =============================================================================
# DEEP ITM PARAMETERS -- AutoResearch will modify these
# =============================================================================

# Bid price in cents for deep ITM YES orders (maker limit)
DEEP_ITM_BID_PRICE = 95

# Maximum simultaneous deep ITM positions
DEEP_ITM_MAX_POSITIONS = 10

# Maximum % of bankroll per single deep ITM position
DEEP_ITM_MAX_POSITION_PCT = 0.05

# Minimum bid-ask spread to place a deep ITM order
DEEP_ITM_MIN_SPREAD = 2


def get_forecast_stdev():
    """Return the FORECAST_STDEV dict used by weather_strategy.py."""
    return {
        0: FORECAST_STDEV_0,
        1: FORECAST_STDEV_1,
        2: FORECAST_STDEV_2,
        3: FORECAST_STDEV_3,
    }


def get_city_weights():
    """Return city weight dict."""
    return {
        "NYC": CITY_WEIGHT_NYC,
        "Chicago": CITY_WEIGHT_CHI,
        "Miami": CITY_WEIGHT_MIA,
        "LA": CITY_WEIGHT_LA,
        "DC": CITY_WEIGHT_DC,
        "Denver": CITY_WEIGHT_DEN,
    }


def get_blend_weights():
    """Return day-dependent blend weights dict used by auto_trade.py."""
    return {
        0: {"hrrr": BLEND_HRRR_DAY0, "gfs": BLEND_GFS_DAY0, "nws": BLEND_NWS_DAY0},
        1: {"hrrr": BLEND_HRRR_DAY1, "gfs": BLEND_GFS_DAY1, "nws": BLEND_NWS_DAY1},
        2: {"hrrr": 0.00, "gfs": BLEND_GFS_DAY2, "nws": BLEND_NWS_DAY2},
    }


def get_strategy_params():
    """Return all current parameters for logging."""
    return {
        "forecast_stdev_0": FORECAST_STDEV_0,
        "forecast_stdev_1": FORECAST_STDEV_1,
        "forecast_stdev_2": FORECAST_STDEV_2,
        "forecast_stdev_3": FORECAST_STDEV_3,
        "edge_threshold_cents": EDGE_THRESHOLD_CENTS,
        "contracts_per_trade": CONTRACTS_PER_TRADE,
        "nws_official_weight": NWS_OFFICIAL_WEIGHT,
        "city_weight_nyc": CITY_WEIGHT_NYC,
        "city_weight_chi": CITY_WEIGHT_CHI,
        "city_weight_mia": CITY_WEIGHT_MIA,
        "city_weight_la": CITY_WEIGHT_LA,
        "city_weight_dc": CITY_WEIGHT_DC,
        "city_weight_den": CITY_WEIGHT_DEN,
        "bucket_multiplier": BUCKET_MULTIPLIER,
        "threshold_multiplier": THRESHOLD_MULTIPLIER,
        "high_confidence_edge": HIGH_CONFIDENCE_EDGE,
        "medium_confidence_edge": MEDIUM_CONFIDENCE_EDGE,
        "max_position_dollars": MAX_POSITION_DOLLARS,
        "min_volume": MIN_VOLUME,
        "tight_ensemble_threshold": TIGHT_ENSEMBLE_THRESHOLD,
        "tight_ensemble_multiplier": TIGHT_ENSEMBLE_MULTIPLIER,
        # Per-strategy edge thresholds
        "crypto_edge_threshold_cents": CRYPTO_EDGE_THRESHOLD_CENTS,
        "sports_edge_threshold_cents": SPORTS_EDGE_THRESHOLD_CENTS,
        "arb_edge_threshold_cents": ARB_EDGE_THRESHOLD_CENTS,
        "exit_edge_threshold_cents": EXIT_EDGE_THRESHOLD_CENTS,
        # Blend weights
        "blend_hrrr_day0": BLEND_HRRR_DAY0,
        "blend_gfs_day0": BLEND_GFS_DAY0,
        "blend_nws_day0": BLEND_NWS_DAY0,
        "blend_hrrr_day1": BLEND_HRRR_DAY1,
        "blend_gfs_day1": BLEND_GFS_DAY1,
        "blend_nws_day1": BLEND_NWS_DAY1,
        "blend_gfs_day2": BLEND_GFS_DAY2,
        "blend_nws_day2": BLEND_NWS_DAY2,
        # Copy-trade parameters
        "copy_min_confidence": COPY_MIN_CONFIDENCE,
        "copy_delay_seconds": COPY_DELAY_SECONDS,
        "copy_size_fraction": COPY_SIZE_FRACTION,
        "copy_max_trades_per_day": COPY_MAX_TRADES_PER_DAY,
        "copy_min_whale_size": COPY_MIN_WHALE_SIZE,
        "copy_trader_weight_0x8dxd": COPY_TRADER_WEIGHT_0x8dxd,
        "copy_crypto_mult": COPY_CRYPTO_MULT,
        "copy_politics_mult": COPY_POLITICS_MULT,
        "copy_sports_mult": COPY_SPORTS_MULT,
        # Tail fade parameters
        "tail_fade_max_price": TAIL_FADE_MAX_PRICE,
        "tail_fade_min_volume": TAIL_FADE_MIN_VOLUME,
        "tail_fade_weather_enabled": TAIL_FADE_WEATHER_ENABLED,
        "tail_fade_crypto_enabled": TAIL_FADE_CRYPTO_ENABLED,
        "tail_fade_nba_enabled": TAIL_FADE_NBA_ENABLED,
        "tail_fade_mid_low": TAIL_FADE_MID_LOW,
        "tail_fade_mid_high": TAIL_FADE_MID_HIGH,
        # NBA underdog parameters
        "underdog_max_price": UNDERDOG_MAX_PRICE,
        "underdog_min_price": UNDERDOG_MIN_PRICE,
        "underdog_max_bet_dollars": UNDERDOG_MAX_BET_DOLLARS,
        "underdog_max_contracts": UNDERDOG_MAX_CONTRACTS,
        "underdog_winner_only": UNDERDOG_WINNER_ONLY,
        # Weather tail parameters
        "weather_tail_max_yes": WEATHER_TAIL_MAX_YES,
        "weather_tail_min_no_prob": WEATHER_TAIL_MIN_NO_PROB,
        "weather_tail_min_edge": WEATHER_TAIL_MIN_EDGE,
        "weather_tail_max_contracts": WEATHER_TAIL_MAX_CONTRACTS,
        # Deep ITM parameters
        "deep_itm_bid_price": DEEP_ITM_BID_PRICE,
        "deep_itm_max_positions": DEEP_ITM_MAX_POSITIONS,
        "deep_itm_max_position_pct": DEEP_ITM_MAX_POSITION_PCT,
        "deep_itm_min_spread": DEEP_ITM_MIN_SPREAD,
    }


# =============================================================================
# STRATEGY LOGIC — AutoResearch agent modifies this function
# =============================================================================
# The backtest harness calls evaluate_market() for each historical market.
# Return {"action": "buy_yes"|"buy_no", "contracts": N} to trade,
# or None / {"action": "skip"} to pass.

def evaluate_market(ticker, series, yes_cents, ask_cents, bid_cents, volume, settled_yes=None):
    """
    Core strategy decision function. Called by backtest_harness.py for each market.

    AutoResearch agent: modify this function to implement new strategies.
    The parameters above are still used by auto_trade.py for live trading.

    Args:
        ticker: Market ticker (e.g., "KXHIGHNY-26MAR21-T60")
        series: Series prefix (e.g., "KXHIGHNY")
        yes_cents: Last YES price in cents (0-100)
        ask_cents: YES ask price in cents
        bid_cents: YES bid price in cents
        volume: Total volume traded
        settled_yes: True if settled YES, False if NO (None during live trading)

    Returns:
        dict with "action" and "contracts", or None to skip.
    """
    # --- Weather tail NO: buy NO on cheap YES weather markets ---
    if series.startswith("KXHIGH"):
        if 0 < yes_cents <= WEATHER_TAIL_MAX_YES and volume >= 10:
            return {"action": "buy_no", "contracts": WEATHER_TAIL_MAX_CONTRACTS}

    # --- Crypto tail NO: same logic for BTC/ETH ---
    if series.startswith(("KXBTC", "KXETH", "KXSOL")):
        if 0 < yes_cents <= WEATHER_TAIL_MAX_YES and volume >= 10:
            return {"action": "buy_no", "contracts": 1}

    # --- NBA underdog YES: buy YES on cheap game winners ---
    if series.startswith("KXNBAGAME"):
        # Skip props, totals, spreads — only game winner markets
        t_upper = ticker.upper()
        if any(kw in t_upper for kw in ["PTS", "TOTAL", "SPREAD", "MENTION"]):
            return None
        if UNDERDOG_MIN_PRICE <= yes_cents <= UNDERDOG_MAX_PRICE and volume >= 50:
            return {"action": "buy_yes", "contracts": min(UNDERDOG_MAX_CONTRACTS, 5)}

    return None
