"""
candidate_strategy.py -- WEATHER FORECAST ARBITRAGE parameters.

This is the file that AutoResearch edits and improves. All parameters
control the weather forecast vs. Kalshi market edge-detection pipeline
in weather_strategy.py.

DO NOT edit this file manually unless you want to reset the strategy.
AutoResearch will evolve it automatically overnight.
"""

# =============================================================================
# WEATHER-SPECIFIC PARAMETERS -- AutoResearch will modify these
# =============================================================================

# Forecast uncertainty: standard deviation in degrees F for NWS forecasts
# Keyed by days_out. Lower = more aggressive (tighter model), higher = more conservative.
FORECAST_STDEV_0 = 1.5   # Same day
FORECAST_STDEV_1 = 2.5   # Tomorrow
FORECAST_STDEV_2 = 3.5   # Day after tomorrow
FORECAST_STDEV_3 = 4.5   # 3 days out

# Edge threshold: minimum edge in cents before we place a trade.
# Too low = many low-quality trades with slippage. Too high = miss good edges.
EDGE_THRESHOLD_CENTS = 3.0

# Position sizing: number of contracts per trade
CONTRACTS_PER_TRADE = 10

# NWS blend ratio: weight given to NWS official forecast vs. ensemble mean.
# 0.0 = pure ensemble, 1.0 = pure NWS official. Currently 40% NWS, 60% ensemble.
NWS_OFFICIAL_WEIGHT = 0.40

# City weights: relative weight for position sizing per city.
# Higher weight = trade more contracts in that city.
CITY_WEIGHT_NYC = 1.0
CITY_WEIGHT_CHI = 1.0
CITY_WEIGHT_MIA = 1.0
CITY_WEIGHT_LA = 1.0

# Market type preference: multiplier on contracts for bucket vs threshold markets.
# >1.0 = prefer that type, <1.0 = trade less of that type.
BUCKET_MULTIPLIER = 1.0
THRESHOLD_MULTIPLIER = 1.0

# Confidence thresholds (edge in cents)
HIGH_CONFIDENCE_EDGE = 10.0   # Above this = "high" confidence
MEDIUM_CONFIDENCE_EDGE = 5.0  # Above this = "medium" confidence

# Maximum position per single market (dollars)
MAX_POSITION_DOLLARS = 5.0

# Minimum volume to consider a market (contracts traded)
MIN_VOLUME = 10

# Ensemble spread filter: if ensemble stdev < this, increase position
# (tighter ensemble = more confident forecast = bigger bet)
TIGHT_ENSEMBLE_THRESHOLD = 2.0
TIGHT_ENSEMBLE_MULTIPLIER = 1.5


def get_forecast_stdev():
    """Return the FORECAST_STDEV dict used by weather_strategy.py."""
    return {
        0: FORECAST_STDEV_0,
        1: FORECAST_STDEV_1,
        2: FORECAST_STDEV_2,
        3: FORECAST_STDEV_3,
    }


def get_city_weights():
    """Return city weight dict."""
    return {
        "NYC": CITY_WEIGHT_NYC,
        "Chicago": CITY_WEIGHT_CHI,
        "Miami": CITY_WEIGHT_MIA,
        "LA": CITY_WEIGHT_LA,
    }


def get_strategy_params():
    """Return all current parameters for logging."""
    return {
        "forecast_stdev_0": FORECAST_STDEV_0,
        "forecast_stdev_1": FORECAST_STDEV_1,
        "forecast_stdev_2": FORECAST_STDEV_2,
        "forecast_stdev_3": FORECAST_STDEV_3,
        "edge_threshold_cents": EDGE_THRESHOLD_CENTS,
        "contracts_per_trade": CONTRACTS_PER_TRADE,
        "nws_official_weight": NWS_OFFICIAL_WEIGHT,
        "city_weight_nyc": CITY_WEIGHT_NYC,
        "city_weight_chi": CITY_WEIGHT_CHI,
        "city_weight_mia": CITY_WEIGHT_MIA,
        "city_weight_la": CITY_WEIGHT_LA,
        "bucket_multiplier": BUCKET_MULTIPLIER,
        "threshold_multiplier": THRESHOLD_MULTIPLIER,
        "high_confidence_edge": HIGH_CONFIDENCE_EDGE,
        "medium_confidence_edge": MEDIUM_CONFIDENCE_EDGE,
        "max_position_dollars": MAX_POSITION_DOLLARS,
        "min_volume": MIN_VOLUME,
        "tight_ensemble_threshold": TIGHT_ENSEMBLE_THRESHOLD,
        "tight_ensemble_multiplier": TIGHT_ENSEMBLE_MULTIPLIER,
    }
