"""
candidate_strategy.py -- WEATHER FORECAST ARBITRAGE parameters.

This is the file that AutoResearch edits and improves. All parameters
control the weather forecast vs. Kalshi market edge-detection pipeline
in weather_strategy.py.

DO NOT edit this file manually unless you want to reset the strategy.
AutoResearch will evolve it automatically overnight.
"""

# =============================================================================
# WEATHER-SPECIFIC PARAMETERS -- AutoResearch will modify these
# =============================================================================

# Forecast uncertainty: standard deviation in degrees F for NWS forecasts
# Keyed by days_out. Lower = more aggressive (tighter model), higher = more conservative.
FORECAST_STDEV_0 = 1.5  # Same day
FORECAST_STDEV_1 = 1.8  # Tomorrow
FORECAST_STDEV_2 = 3.5   # Day after tomorrow
FORECAST_STDEV_3 = 4.5   # 3 days out

# Edge threshold: minimum edge in cents before we place a trade.
# Too low = many low-quality trades with slippage. Too high = miss good edges.
EDGE_THRESHOLD_CENTS = 5.0

# Position sizing: number of contracts per trade
CONTRACTS_PER_TRADE = 25

# NWS blend ratio: weight given to NWS official forecast vs. ensemble mean.
# 0.0 = pure ensemble, 1.0 = pure NWS official. Currently 40% NWS, 60% ensemble.
NWS_OFFICIAL_WEIGHT = 0.3

# City weights: relative weight for position sizing per city.
# Higher weight = trade more contracts in that city.
CITY_WEIGHT_NYC = 1.0
CITY_WEIGHT_CHI = 1.5
CITY_WEIGHT_MIA = 1.0
CITY_WEIGHT_LA = 1.0
CITY_WEIGHT_DC = 1.0
CITY_WEIGHT_DEN = 1.0

# Market type preference: multiplier on contracts for bucket vs threshold markets.
# >1.0 = prefer that type, <1.0 = trade less of that type.
BUCKET_MULTIPLIER = 1.0
THRESHOLD_MULTIPLIER = 1.0

# Confidence thresholds (edge in cents)
HIGH_CONFIDENCE_EDGE = 7.0  # Above this = "high" confidence
MEDIUM_CONFIDENCE_EDGE = 5.0  # Above this = "medium" confidence

# Maximum position per single market (dollars)
MAX_POSITION_DOLLARS = 7.0

# Minimum volume to consider a market (contracts traded)
MIN_VOLUME = 10

# Ensemble spread filter: if ensemble stdev < this, increase position
# (tighter ensemble = more confident forecast = bigger bet)
TIGHT_ENSEMBLE_THRESHOLD = 2.0
TIGHT_ENSEMBLE_MULTIPLIER = 1.5


# =============================================================================
# COPY-TRADE PARAMETERS -- AutoResearch will modify these
# =============================================================================

# Minimum confidence to auto-copy a trade (0.0-1.0)
COPY_MIN_CONFIDENCE = 0.8

# How quickly to react after detecting a whale trade (seconds)
# Lower = more aggressive, higher = wait for confirmation
COPY_DELAY_SECONDS = 60

# Position sizing as fraction of what the whale trades
COPY_SIZE_FRACTION = 0.01  # 1% of whale's position

# Maximum copy trades per day
COPY_MAX_TRADES_PER_DAY = 10

# Minimum whale trade size to copy (USD)
COPY_MIN_WHALE_SIZE = 100.0

# Weight per tracked trader (how much to trust their signals)
COPY_TRADER_WEIGHT_0x8dxd = 1.0

# Which categories to copy (multiplier: 0 = skip, 1 = normal, 2 = double)
COPY_CRYPTO_MULT = 1.5
COPY_POLITICS_MULT = 0.0  # Don't copy politics initially
COPY_SPORTS_MULT = 0.5


# =============================================================================
# CRYPTO PARAMETERS -- AutoResearch will modify these
# =============================================================================

# Minimum edge in cents to flag a crypto range market (4¢ = 4 percentage points)
CRYPTO_MIN_EDGE_CENTS = 4.0

# Position sizing for crypto trades
CRYPTO_CONTRACTS_PER_TRADE = 5
CRYPTO_MAX_POSITION_DOLLARS = 5.0

# Volatility bias: multiplicative adjustment to realized vol before computing fair value.
# >1.0 = assume more vol than measured (conservative, fewer center-bucket bets).
# <1.0 = assume less vol than measured (aggressive, more center-bucket bets).
CRYPTO_VOL_BIAS_BTC = 1.0  # Bitcoin vol adjustment
CRYPTO_VOL_BIAS_ETH = 1.0  # Ethereum vol adjustment
CRYPTO_VOL_BIAS_SOL = 1.0  # Solana vol adjustment

# Bucket bias corrections:
# Center bias < 1.0 discounts YES fair value for center buckets (retail overprices center).
# Tail multiplier > 1.0 boosts YES fair value for tail buckets (retail underprices tails).
CRYPTO_CENTER_BUCKET_BIAS = 0.95   # scale fair_yes for buckets within 1 sigma
CRYPTO_TAIL_BUCKET_MULTIPLIER = 1.0  # scale fair_yes for buckets beyond 1 sigma


# =============================================================================
# SPORTS PARAMETERS -- AutoResearch will modify these
# =============================================================================

# Home court advantage in NBA (points added to home team's adjusted differential)
SPORTS_HOME_COURT_ADVANTAGE = 3.2

# Standard deviation of NBA game margin (calibrates logistic win probability)
SPORTS_NBA_GAME_STDEV = 11.5

# Weight for recent form (last 10 games) vs season-long stats
SPORTS_RECENT_FORM_WEIGHT = 0.30

# Minimum edge (percentage points) to flag a sports market
SPORTS_MIN_EDGE_PCT = 5.0

# Position sizing for sports trades
SPORTS_CONTRACTS_PER_TRADE = 5
SPORTS_MAX_POSITION_DOLLARS = 5.0


def get_forecast_stdev():
    """Return the FORECAST_STDEV dict used by weather_strategy.py."""
    return {
        0: FORECAST_STDEV_0,
        1: FORECAST_STDEV_1,
        2: FORECAST_STDEV_2,
        3: FORECAST_STDEV_3,
    }


def get_city_weights():
    """Return city weight dict."""
    return {
        "NYC": CITY_WEIGHT_NYC,
        "Chicago": CITY_WEIGHT_CHI,
        "Miami": CITY_WEIGHT_MIA,
        "LA": CITY_WEIGHT_LA,
        "DC": CITY_WEIGHT_DC,
        "Denver": CITY_WEIGHT_DEN,
    }


def get_strategy_params():
    """Return all current parameters for logging."""
    return {
        "forecast_stdev_0": FORECAST_STDEV_0,
        "forecast_stdev_1": FORECAST_STDEV_1,
        "forecast_stdev_2": FORECAST_STDEV_2,
        "forecast_stdev_3": FORECAST_STDEV_3,
        "edge_threshold_cents": EDGE_THRESHOLD_CENTS,
        "contracts_per_trade": CONTRACTS_PER_TRADE,
        "nws_official_weight": NWS_OFFICIAL_WEIGHT,
        "city_weight_nyc": CITY_WEIGHT_NYC,
        "city_weight_chi": CITY_WEIGHT_CHI,
        "city_weight_mia": CITY_WEIGHT_MIA,
        "city_weight_la": CITY_WEIGHT_LA,
        "city_weight_dc": CITY_WEIGHT_DC,
        "city_weight_den": CITY_WEIGHT_DEN,
        "bucket_multiplier": BUCKET_MULTIPLIER,
        "threshold_multiplier": THRESHOLD_MULTIPLIER,
        "high_confidence_edge": HIGH_CONFIDENCE_EDGE,
        "medium_confidence_edge": MEDIUM_CONFIDENCE_EDGE,
        "max_position_dollars": MAX_POSITION_DOLLARS,
        "min_volume": MIN_VOLUME,
        "tight_ensemble_threshold": TIGHT_ENSEMBLE_THRESHOLD,
        "tight_ensemble_multiplier": TIGHT_ENSEMBLE_MULTIPLIER,
        # Copy-trade parameters
        "copy_min_confidence": COPY_MIN_CONFIDENCE,
        "copy_delay_seconds": COPY_DELAY_SECONDS,
        "copy_size_fraction": COPY_SIZE_FRACTION,
        "copy_max_trades_per_day": COPY_MAX_TRADES_PER_DAY,
        "copy_min_whale_size": COPY_MIN_WHALE_SIZE,
        "copy_trader_weight_0x8dxd": COPY_TRADER_WEIGHT_0x8dxd,
        "copy_crypto_mult": COPY_CRYPTO_MULT,
        "copy_politics_mult": COPY_POLITICS_MULT,
        "copy_sports_mult": COPY_SPORTS_MULT,
    }
